---
single_line_string: This is a single-line string.

multi_line_string: |
  This is a multi-line string.
  It can span multiple lines.
  Each line will be preserved.

boolean_true: true

boolean_false: false

null_value: null

date: 2023-10-01

time: 2023-10-01T12:00:00Z

regex: ^[a-zA-Z0-9_]+$

config:
  version: 1
  name: Sample Configuration
  description: This is a sample configuration file.

fruits:
  - name: apple
    color: red
    weight: 150
  - name: banana
    color: yellow
    weight: 120
  - name: cherry
    color: red
    weight: 10

nested:
  level1:
    level2:
      level3:
        key: value
        list:
          - item1
          - item2
          - item3

mixed:
  integer: 42
  float: 3.14
  string: Hello, World!
  boolean: true
  list:
    - item1
    - item2
    - item3
  dict:
    key1: value1
    key2: value2

  # Add a blank line below this comment to resolve the error
