on: [push, pull_request]

jobs:
  build:
    name: YAML Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Set up Ruby 3.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - name: Run YAML Lint
        env:
          INCLUDE_FILES: "config.yml, another-config.yml"
          EXCLUDE_FILES: "README.md"
          SHOW_ERRORS: "true"
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/yaml-lint/master/pipeline.sh)